const table=new hashTable(50)
table.set('name','Cristiano')
table.set('age',38)
table.display()
table.set('mane','Neymar')
table.display()
table.remove('mane')
table.display()
console.log('--------------')
console.log(table.get('name'))